### ISSUE TITLE
[Feature Request] Search Self?

### ISSUE THREAD

**Issue by icsy7867** [gethomepage/homepage#1127]
### Description

Perhaps this is already done but I am not configuring it correctly.  I am coming here from FLAME, as it is no longer actively developed.  Love your work and design!

I am planning/testing out pages that might be 50+ bookmarks as a resource hub for where I work.  Since there are so many possible links, I would want users to be able to search for:
"Policies" or "Meeting" or "Application" to find specific things (Just as an example). 

In the search bar, I would think there could be a "SELF" option.  I dont care about using other search engines, but I would like to be able to search and to show a list of matching results.

Apologies if this is already implemented somehow.  I did not see a relevant issue, or anything in the wiki.

**Comment by alekslyse** [comment]
Is not this what you are looking for? https://gethomepage.dev/en/configs/settings/#quick-launch

**Comment by icsy7867** [comment]
I actually didn't even realize that was there.  Yes! That is very close.  However I might have 200+ people using the links/bookmarks/items on this page.  Some of them are technical folks, some of them arent.  So this isnt intuitive to someone that doesnt know the feature exists.

I would love for the search bar at the top to be able to filter the links/pages/bookmarks/etc below.  I think having a search provider for "Self" that only sorts/filters items based on the input criteria would make sense.

**Comment by shamoon** [comment]
As quicklaunch does this exact thing I don’t see why we would re-implement the feature for the search bar which is meant to represent web search
