### ISSUE TITLE
[Bug] Uptime Kuma widget ignores port in URL

### ISSUE THREAD

**Issue by capnsmc** [gethomepage/homepage#1459]
### Description

When configuring Uptime Kuma to use its widget the widget seems to ignore the port number.

### Steps to reproduce

This is part of my configuration:

```
    - Uptime Kuma:
        href: http://host:3001/dashboard
        icon: uptime-kuma
        server: local-docker
        container: uptime-kuma
        widget:
          type: uptimekuma
          url: http://host:3001
          slug: whatever
```

This is the log entry:

```
[2023-05-04T16:05:18.489Z] error: <httpProxy> Error calling http://host/api/status-page/heartbeat/whatever...
[2023-05-04T16:05:18.489Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 127.0.1.1:3001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.1.1',
    port: 3001
  }
]
```

Note that the URL in the first line is wrong, because it is missing the port number. It should be http://host:3001/api/status-page/heartbeat/whatever (which would work as I have changed the URL like that and pasted it into a browser).

### homepage version

v0.6.17 (f692e71, May 1, 2023)

### Installation method

Docker

### Configuration

```yaml
- Uptime Kuma:
        href: http://host:3001/dashboard
        icon: uptime-kuma
        server: local-docker
        container: uptime-kuma
        widget:
          type: uptimekuma
          url: http://host:3001
          slug: whatever
```

### Container Logs

[2023-05-04T16:05:18.489Z] error: <httpProxy> Error calling http://host/api/status-page/heartbeat/whatever...
[2023-05-04T16:05:18.489Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 127.0.1.1:3001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.1.1',
    port: 3001
  }
]

### Troubleshooting

```
$ sudo docker exec homepage ping host
PING host (127.0.1.1): 56 data bytes
64 bytes from 127.0.1.1: seq=0 ttl=64 time=0.035 ms
64 bytes from 127.0.1.1: seq=1 ttl=64 time=0.050 ms
64 bytes from 127.0.1.1: seq=2 ttl=64 time=0.050 ms
64 bytes from 127.0.1.1: seq=3 ttl=64 time=0.051 ms
```

Wrong URL:

```
$ curl -L -k http://host/api/status-page/heartbeat/whatever
curl: (7) Failed to connect to host port 80 after 0 ms: Connection refused
```

Corrected URL (with --silent and piped into _tail_ so that this entry won't be too long):

```
$ curl --silent -L -k http://host:3001/api/status-page/heartbeat/whatever | head -c 219
{"heartbeatList":{"1":[{"status":1,"time":"2023-05-04 15:55:23.554","msg":"","ping":53},{"status":1,"time":"2023-05-04 15:55:53.654","msg":"","ping":161},{"status":1,"time":"2023-05-04 15:56:23.844","msg":"","ping":37},
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
It has the port in the error. The log output is just misleading, I should fix that. Is that curl from inside the homepage container? Guessing not
