### ISSUE TITLE
[Bug] Issue with displaying sonarr queue list

### ISSUE THREAD

**Issue by pwsnla** [gethomepage/homepage#1801]
### Description

I experienced an issue with display of the sonarr queue (enabled with enableQueue option in sonarr widget).

Initially queue is displayed correctly but list of episodes being downloaded got replicated every time with different time remaining every time I left "Homepage" tab and returned to it:

![Screenshot 2023-08-11 144848](https://github.com/benphelps/homepage/assets/38261406/7948475c-edd8-4439-b62c-3ca735c26dbb)

8 episodes were being downloaded but as can be seen the list shows 40 items. I was using Firefox browser, in case it matters.

### Steps to reproduce

enable enableQueue: true option in sonarr widget.
Start download of multiple episdoes in sonarr. After queue is displayed move away to a different tab and return to Homepage tab.

### homepage version

v0.6.28 (63a5622, Aug 4, 2023)

### Installation method

Docker

### Troubleshooting

I closed and reopened Homepage tab and the queue was displayed correctly. The issue occurs only if Homage is left open.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I cant reproduce this, regardless of refreshes etc. There may be something more specific here but based off how react works I dont get how it would happen. Maybe try re-creating your container.

<img width="749" alt="Screenshot 2023-08-11 at 2 05 12 PM" src="https://github.com/benphelps/homepage/assets/4887959/7ea1eb64-6159-40a8-b9c2-f054f689d3b0">
<img width="761" alt="Screenshot 2023-08-11 at 2 05 02 PM" src="https://github.com/benphelps/homepage/assets/4887959/14c38f7b-5371-4b53-a898-39201894392e">

It almost looks like youre seeing cached data (time is lower on each batch) but each proxied call to sonar should only contain 1 batch, e.g.
```
[
    {
        "trackedDownloadState": "downloading",
        "trackedDownloadStatus": "ok",
        "timeLeft": "00:00:49",
        "size": 4628970209,
        "sizeLeft": 2994114396,
        "seriesId": 123,
        "episodeTitle": "*",
        "episodeId": 12345,
        "status": "downloading"
    },
    {
        "trackedDownloadState": "downloading",
        "trackedDownloadStatus": "ok",
        "timeLeft": "00:02:05",
        "size": 4656012984,
        "sizeLeft": 4656012984,
        "seriesId": 123,
        "episodeTitle": "*",
        "episodeId": 12345,
        "status": "downloading"
    },
    {
        "trackedDownloadState": "downloading",
        "trackedDownloadStatus": "ok",
        "timeLeft": "00:03:21",
        "size": 4649344040,
        "sizeLeft": 4649344040,
        "seriesId": 123,
        "episodeTitle": "*",
        "episodeId": 12345,
        "status": "downloading"
    },
    {
        "trackedDownloadState": "downloading",
        "trackedDownloadStatus": "ok",
        "timeLeft": "00:04:37",
        "size": 4634695434,
        "sizeLeft": 4634695434,
        "seriesId": 123,
        "episodeTitle": "*",
        "episodeId": 12345,
        "status": "downloading"
    },
    {
        "trackedDownloadState": "downloading",
        "trackedDownloadStatus": "ok",
        "timeLeft": "00:05:53",
        "size": 4585485762,
        "sizeLeft": 4585485762,
        "seriesId": 123,
        "episodeTitle": "*",
        "episodeId": 12345,
        "status": "downloading"
    },
    {
        "trackedDownloadState": "downloading",
        "trackedDownloadStatus": "ok",
        "timeLeft": "00:07:08",
        "size": 4622961868,
        "sizeLeft": 4622961868,
        "seriesId": 123,
        "episodeTitle": "*",
        "episodeId": 12345,
        "status": "downloading"
    },
    {
        "trackedDownloadState": "downloading",
        "trackedDownloadStatus": "ok",
        "timeLeft": "00:08:24",
        "size": 4616974499,
        "sizeLeft": 4616974499,
        "seriesId": 123,
        "episodeTitle": "*",
        "episodeId": 12345,
        "status": "downloading"
    },
    {
        "trackedDownloadState": "downloading",
        "trackedDownloadStatus": "ok",
        "timeLeft": "00:09:40",
        "size": 4624251617,
        "sizeLeft": 4624251617,
        "seriesId": 123,
        "episodeTitle": "*",
        "episodeId": 12345,
        "status": "downloading"
    }
]
```

Happy to re-address if there more to it.
