### ISSUE TITLE
[Bug] base and startUrl invalid

### ISSUE THREAD

**Issue by iamckun** [gethomepage/homepage#2128]
### Description

base and startUrl invalid setting 

### Steps to reproduce

After setting the base: http://host.local/homepage
After that, we can only pass through http://host.local/ Unable to access homepage

### homepage version

v 0.7.2

### Installation method

Docker

### Configuration

```yaml
base: http://host.local/homepage
startUrl: http://host.local/homepage
```

### Troubleshooting

After setting the base: http://host.local/homepage
After that, we can only pass through http://host.local/ Unable to access homepage

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by iamckun** [comment]
> 此设置在很长一段时间内没有更改。您没有提供任何信息，但使用将非常依赖于您的反向代理和安装，它不仅会神奇地更改实例 URL。如果设置它破坏了您的安装，也许不要设置它？`base`
> 
> 随意提供更多背景信息

Need to access it under /homepage

settings.yaml
~~~yaml
base: https://ckun.com/homepage
startUrl: https://ckun.com/homepage
~~~

nginx.conf
~~~nginx
server {
  server_name ckun.com;
  listen 443 ssl http2;
  ssl_certificate /opt/ssl/ckun.com/fullchain.cer;
  ssl_certificate_key /opt/ssl/ckun.com/ckun.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  listen 80;
  location /homepage {
    proxy_pass http://localhost:3000/homepage;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
~~~

![image](https://github.com/gethomepage/homepage/assets/65990499/b1ed4bec-261c-4e23-9f2f-4048d9bcc8ba)

I want to access the application homepage in the /homepage directory

**Comment by shamoon** [comment]
You can take a look at https://github.com/gethomepage/homepage/issues/539

In short, we have limited control over this because the base is compiled at build time. If you cant do it with your RP you may need to run from source
