### ISSUE TITLE
[Bug] statusStyle 'dot' broken in 0.7.2

### ISSUE THREAD

**Issue by vladaurosh** [gethomepage/homepage#2139]
### Description

Upgraded from 0.7.0 to 0.7.2 and ping status does not work if set to 'dot'. Actually it does work if device is down (red dot)
If set to basic or nothing it works fine.
![image](https://github.com/gethomepage/homepage/assets/47857324/850ff74b-f8ea-4f89-b79c-31296c702640)

### Steps to reproduce

statusStyle: dot
does not work for devices that are up.
Works fine if set to basic or not set.

### homepage version

0.7.2

### Installation method

Source

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I forgot to release the fix. Please try `main` and let me know if any issues and ill release

**Comment by shamoon** [comment]
@vladaurosh all good?

**Comment by vladaurosh** [comment]
Yep, fixed in main. Thanks for quick response.

**Comment by shamoon** [comment]
Awesome, thanks for the report
