### ISSUE TITLE
[Bug] Memory stats not correct in docker integrated widgets

### ISSUE THREAD

**Issue by Koro33** [gethomepage/homepage#2163]
### Description

The Memory stats are not correct in docker integrated widget. For example, there is two qbittorrent container in my system. 

![image](https://github.com/gethomepage/homepage/assets/9485531/3031bf5d-08dc-426d-af3f-543f21c1d00c)

Above is the screenshot at the same time. The output in terminal is generated by `docker stats`. The values in widgets are much larger than the values in terminal output. (qbittorrent is an example, it happened in every docker widget not just in qbittorrent)

### Steps to reproduce

1. deploy a docker container and add it in the widget.
2. execute `docker stats` in terminal

### homepage version

v0.7.3

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
The stats come from the docker api, we don’t do anything to them

**Comment by shamoon** [comment]
They are oddly different, you can see if re-creating makes a difference. But again, this is what we get back from the api, should be easy enough to verify that

**Comment by Koro33** [comment]
Perhaps I know the reason after searched and tested a lot. 
Read the first `note` in [https://docs.docker.com/engine/reference/commandline/stats/#description](https://docs.docker.com/engine/reference/commandline/stats/#description)

In the new version of docker there is no field of `cache` but `inactive_file` in the api.

In this project, the memory usage is calculated by the function below which still used `cache`

https://github.com/gethomepage/homepage/blob/4a0434751841b1d38bde60cdfdade71f58b3b9e3/src/widgets/docker/stats-helpers.js#L14

**Comment by shamoon** [comment]
Docker 19.03 was released before this project was created. What is the actual output from the docker api for your containers here?

**Comment by Koro33** [comment]
like that, only keep the related section

```json
...
"memory_stats": {
        "usage": 12548222976,
        "stats": {
            "active_anon": 22409216,
            "active_file": 3650707456,
            "anon": 44994560,
            "anon_thp": 0,
            "file": 11738656768,
            "file_dirty": 44535808,
            "file_mapped": 3079168000,
            "file_writeback": 0,
            "inactive_anon": 22724608,
            "inactive_file": 8087924736,
            "kernel_stack": 425984,
            "pgactivate": 70451928,
            "pgdeactivate": 77867101,
            "pgfault": 34908848,
            "pglazyfree": 0,
            "pglazyfreed": 0,
            "pgmajfault": 172197,
            "pgrefill": 78344838,
            "pgscan": 288074379,
            "pgsteal": 203194911,
            "shmem": 0,
            "slab": 262322304,
            "slab_reclaimable": 260135192,
            "slab_unreclaimable": 2187112,
            "sock": 2818048,
            "thp_collapse_alloc": 0,
            "thp_fault_alloc": 0,
            "unevictable": 0,
            "workingset_activate": 0,
            "workingset_nodereclaim": 2533898,
            "workingset_refault": 0
        },
        "limit": 16728547328
    },
...
```

**Comment by Koro33** [comment]
Another infomation that maybe useful.

In the official api [doc](https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerStats), it describe the calculate of memory as `used_memory = memory_stats.usage - memory_stats.stats.cache`

**Comment by shamoon** [comment]
Well yea that is confusing, that last link (thanks) really makes it sound like what we're doing is correct. The docs before are referring to cli but it's confusing because they reference `total_inactive_file` and `inactive_file`. And yes, my stats (and presumably most people) are similar to yours in that they dont contain `cache` and do contain `inactive_file`.

And again, confusingly, the cli docs state "If you need more detailed information about a container's resource usage, use the /containers/(id)/stats API endpoint.", which makes it sound like the API is "better"

A change for this would be pretty straightforward, assuming you're right, but last thing to check is if we make this change the stats for that sample API output above would be:
12548222976 - 8087924736 = 4,460,298,240 = 4.4 GB, is that correct for the container those stats are from? For me, its still not the same as via cli, though slightly closer

**Comment by shamoon** [comment]
Also, this: https://github.com/docker/cli/blob/dcc161076861177b5eef6cb321722520db3184e7/cli/command/container/stats_helpers.go#L239 supports the change and implies their docs are wrong

**Comment by shamoon** [comment]
I went ahead and merged the change, appreciate you digging into it more.

I am still curious to know if what you get is now the same as cli. Anyway, you can test in the `main` image [once it finishes building](https://github.com/gethomepage/homepage/actions/runs/6449025150) in ~20 minutes

**Comment by Koro33** [comment]
Yes, it's not the same but closer

![image](https://github.com/gethomepage/homepage/assets/9485531/d75e09b9-7536-4477-a460-2dcb922bf664)

Anyway, the value of memory looks much 'normal' now. Thx for your work.

**Comment by Koro33** [comment]
`docker stats` use `GiB` `MiB` as unit, which is 1024 based. Perhaps that's the reason why they show different values.
