### ISSUE TITLE
[Bug] On a dual-stack network, ping for a single-stack (IPv4 or IPv6 only) service may fail

### ISSUE THREAD

**Issue by saiarcot895** [gethomepage/homepage#2211]
### Description

When:

* homepage has access to a dual-stack network (i.e. has both an IPv4 and IPv6 address),
* a domain name is used for pinging a service to check to see if it's up,
* that domain has both an IPv4 and IPv6 address record,
* the service is only listening on IPv4

Then the ping may fail with a 500 error. This appears to be because Node 18, by default, doesn't enable the Happy Eyeballs algorithm by default (see nodejs/node#41625, implemented in nodejs/node#44731). This means that if a connection over IPv6 fails, then it doesn't automatically fall back to trying with IPv4. It looks like it will be enabled by default in Node 20, but for Node 18, `autoSelectFamily: true` would need to be set when making the HTTP request.

### Steps to reproduce

1. Have an environment/network setup with both IPv4 and IPv6 configured.
2. Host a service that's listening on IPv4 only.
3. Have a DNS entry/domain name with both A (IPv4) and AAAA (IPv6) records.
4. Use that domain name for pinging from homepage.

### homepage version

v0.7.4 (8ec488e, Oct 18, 2023)

### Installation method

Docker

### Troubleshooting

I did a packet capture to see what was happening with the pings, and saw that only IPv6 was being attempted. The IPv4 connection at the end was me manually using the IPv4 address in a `wget` test from the homepage container.

![image](https://github.com/gethomepage/homepage/assets/5923875/564b6f51-d77e-4a45-966f-d23776b3931a)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I dont really know how common a situation this is and I did encounter some issues with including this option testing via https for sites that dont specify AAAA records, but overall I think the change is low risk and as noted, will be default in node 20
