### ISSUE TITLE
[Bug] authentik widget fails with authentik 2023.10.1

### ISSUE THREAD

**Issue by jcollas** [gethomepage/homepage#2250]
### Description

The authentik widget has this error with Authentik 2023.10.1

API Error: The string did not match the expected pattern.

### Steps to reproduce

1. Configure the authentik widget
2. It works under authentik 2023.08, but fails in 2023.10.1

### homepage version

Kubernetes, v0.7.4

### Installation method

Other (please describe above)

### Troubleshooting

The widget returns the following error string:

API Error: The string did not match the expected pattern.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
https://github.com/gethomepage/homepage/issues/2243
