### ISSUE TITLE
[Bug] Ping always shows "down" on nightly docker image

### ISSUE THREAD

**Issue by romner-set** [gethomepage/homepage#2253]
### Description

Adding a `ping` property to any service always shows "down", no matter if the service is actually reachable. I'm pretty sure this a problem specifically caused by the new true ping implementation, since the `:latest` docker image works fine if `ping` is set to `http://<host>`.

### Steps to reproduce

1. Create a service
2. Add `ping: <anything>`

### homepage version

`ghcr.io/gethomepage/homepage:nightly`

### Installation method

Docker

### Configuration

```yaml
- Group A:
    - Service 1:
        href: https://example.com
        ping: 10.0.0.4
```

### Browser Logs

The API request to `/api/ping?group=xxxxx&service=xxxxxx` returns this:
```json
{
    "inputHost": "10.0.0.4",
    "host": "10.0.0.4",
    "alive": false,
    "output": "PING 10.0.0.4 (10.0.0.4): 56 data bytes\n\n--- 10.0.0.4 ping statistics ---\n1 packets transmitted, 0 packets received, 100% packet loss\n",
    "time": "unknown",
    "times": [],
    "min": "unknown",
    "max": "unknown",
    "avg": "unknown",
    "stddev": "unknown",
    "packetLoss": "100.000",
    "numeric_host": "10.0.0.4)"
}
```
I assume there's a typo somewhere that adds an extra `)` to the numeric host.

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
It does not in fact, always show down and the output above shows its working:

> 1 packets transmitted, 0 packets received, 100% packet loss

That is down

<img width="147" alt="Screenshot 2023-10-28 at 4 10 27 PM" src="https://github.com/gethomepage/homepage/assets/4887959/c4694a25-6f98-4dfb-8d57-0ebcb1d7c955">

If you want to check http, use siteMonitor, its true they are not the same

**Comment by romner-set** [comment]
> It does not in fact, always show down and the output above shows its working:
> 
> > 1 packets transmitted, 0 packets received, 100% packet loss
> 
> That is down
> 
> <img alt="Screenshot 2023-10-28 at 4 10 27 PM" width="147" src="https://user-images.githubusercontent.com/4887959/278841452-c4694a25-6f98-4dfb-8d57-0ebcb1d7c955.png">
> 
> If you want to check http, use siteMonitor, its true they are not the same

The output says "100% packet loss", meaning the site was unreachable.

The actual problem was that I had ICMP requests blocked in my firewall, nothing to do with homepage... sorry for wasting your time, and thanks for replying so quickly. It's still weird that the `numeric_host` has an extra `)` at the end, though.
