### ISSUE TITLE
[Bug] Other Video counted as Movies in widget

### ISSUE THREAD

**Issue by dontcrash** [gethomepage/homepage#2268]
### Description
![image](https://github.com/gethomepage/homepage/assets/32660358/6b68483c-2fb9-4ed2-98bb-1a1c548339cd)
![image](https://github.com/gethomepage/homepage/assets/32660358/bf5f1cf1-b740-4b94-842f-df99117dd56b)
![image](https://github.com/gethomepage/homepage/assets/32660358/13908bb1-d6d2-4972-bcef-847165ee3ca4)

I suspect the issue is with the logic in /src/widgets/plex/proxy.js

```javascript
  let libraries = cache.get(`${librariesCacheKey}.${service}`);
  if (libraries === null) {
    logger.debug("Getting libraries from Plex API");
    [status, apiData] = await fetchFromPlexAPI("/library/sections", widget);
    if (apiData && apiData.MediaContainer) {
      libraries = [].concat(apiData.MediaContainer.Directory);
      cache.put(`${librariesCacheKey}.${service}`, libraries, 1000 * 60 * 60 * 6);
    }
  }

  let albums = cache.get(`${albumsCacheKey}.${service}`);
  let movies = cache.get(`${moviesCacheKey}.${service}`);
  let tv = cache.get(`${tvCacheKey}.${service}`);
  if (albums === null || movies === null || tv === null) {
    albums = 0;
    movies = 0;
    tv = 0;
    logger.debug("Getting counts from Plex API");
    const movieTVLibraries = libraries.filter((l) => ["movie", "show", "artist"].includes(l._attributes.type));
    await Promise.all(
      movieTVLibraries.map(async (library) => {
        const libraryURL = ["movie", "show"].includes(library._attributes.type)
          ? `/library/sections/${library._attributes.key}/all` // tv + movies
          : `/library/sections/${library._attributes.key}/albums`; // music
        [status, apiData] = await fetchFromPlexAPI(libraryURL, widget);
        if (apiData && apiData.MediaContainer) {
          const size = parseInt(apiData.MediaContainer._attributes.size, 10);
          if (library._attributes.type === "movie") {
            movies += size;
          } else if (library._attributes.type === "show") {
            tv += size;
          } else if (library._attributes.type === "artist") {
            albums += size;
          }
        }
      }),
    );
```

### Steps to reproduce

Add a Plex widget, ensure your Plex server has at least one 'Other Video" library, in my case training video libraries that are not Movies.

### homepage version

Latest

### Installation method

Docker

### Configuration

```yaml
N/A
```

### Container Logs

N/A

### Browser Logs

N/A

### Troubleshooting

Counted all the other video libraries on my Plex server, those plus the Movies library make up the incorrect count, my library only has 711 movies.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
If Plex considers the library type "movie" then it will be counted, thats what the above code does. What does the plex API return for the video (non-movie) library?

**Comment by dontcrash** [comment]
Unfortunately Plex returns these as a Movie type, even though they are listed as Other videos: 

{id: 116211993, key: 24, title: "VCP6-DCV", type: "movie"}

![image](https://github.com/gethomepage/homepage/assets/32660358/b1862936-08ff-44ea-8a01-03e76c3c64ca)


The only way to change this behaviour would be to allow users to manually specify the key or ID of their movie libraries.

**Comment by shamoon** [comment]
Yea, so feel free to open a FR, but this is a weakness of the plex API
