### ISSUE TITLE
[Bug] Immich API Endpoint needs updating

### ISSUE THREAD

**Issue by neslieang** [gethomepage/homepage#2286]
### Description

Immich Service Widget needs to be updated to match breaking change in recent Immich release where endpoint has been changed to server-info/stats to server-info/statistics

https://github.com/immich-app/immich/releases/tag/v1.85.0

### Steps to reproduce

Load Immich Service Widget on Homepage

### homepage version

v0.7.4

### Installation method

Docker

### Troubleshooting

404 error on missing endpoint due to update

[2023-11-08T22:51:33.348Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://immich.*.*.*/api/server-info/stats

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please search
