### ISSUE TITLE
[Bug] Ping values seem incorrect since v 0.8.0

### ISSUE THREAD

**Issue by Chacsam** [gethomepage/homepage#2300]
### Description

Since update to v 0.8.0 it seems that all ping values are off, either too low to be true or "Down"
![image](https://github.com/gethomepage/homepage/assets/28670803/24655817-f29e-466a-a5f2-32e8336d1ce2)

### Steps to reproduce

Add ping on any service
Display dashboard

### homepage version

0.8.0

### Installation method

Docker

### Troubleshooting

Different applications/devices tested

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please search, read the release notes

**Comment by Chacsam** [comment]
Sorry I missed it :(

**Comment by luweijun1992** [comment]
Same problem
The ping results are all 0ms

**Comment by Chacsam** [comment]
I didn't fully understand the reason behind the change (it sounded very academic to me), but the solution is to replace `ping` by `siteMonitor` in your services.yaml

**Comment by benphelps** [comment]
> Just another example of changes for the sake of changes since shamoon came on the project. Even if the underlying code for how 'ping' worked changed, I don't see any good reason why anyone should have had to go and reconfigure their yaml file to change 'ping' to 'siteMonitor'. Ludicrous. But you're not allowed to criticize anything he does, so the nonsense will continue.

You're wrong in pretty much every respect here. @shamoon has been on the project from the very start. But please, let me check the contributions you've made to the project... oh right. This is free software, built by people using their own very-not-free time.  The fact you feel entitled to complain about something you've given absolutely nothing back to, is quite insane to me.  By all means, go start your own project with your own `ping`, and it'll be just how you want.

---

This wasn't a change for the sake of change, this was fixing a misleading feature while allowing the existing feature to continue being used.

`ping` has a very well established meaning, and is an actual network utility, so leaving it as a timed HTTP HEAD request, is just not what a ping is, and is fundamentally misleading.

**Comment by shamoon** [comment]
I have no idea what your problem is, the level of entitlement and obnoxiousness is off the charts. The change was requested by multiple people, you troll. The change is in the docs, in the release notes and the PR was out there just like anything else. Really, your comments do not help this project in any way or add any value, please stop.
