### ISSUE TITLE
[Bug] Stats only show network stats of one interface

### ISSUE THREAD

**Issue by prokrypt** [gethomepage/homepage#2333]
### Description

Some service stats will show 0B RX and 0B TX. Others may show inaccurate values. `docker stats` show the correct values (I think).

Here's a snippet from dozzle's stats, obtained from the docker proxy:
```
 "name": "/dozzle_app.3avweckmnjl8edf80evnhkeye.p0hu01kv9loufxwoo5kbjg8or",
   "networks": {
      "eth0": {
         "rx_bytes": 0,
         "rx_dropped": 0,
         "rx_errors": 0,
         "rx_packets": 0,
         "tx_bytes": 0,
         "tx_dropped": 0,
         "tx_errors": 0,
         "tx_packets": 0
      },
      "eth1": {
         "rx_bytes": 6004218,
         "rx_dropped": 0,
         "rx_errors": 0,
         "rx_packets": 90960,
         "tx_bytes": 15474952,
         "tx_dropped": 0,
         "tx_errors": 0,
         "tx_packets": 92913
      },
      "eth2": {
         "rx_bytes": 119712930,
         "rx_dropped": 0,
         "rx_errors": 0,
         "rx_packets": 111921,
         "tx_bytes": 7374969,
         "tx_dropped": 0,
         "tx_errors": 0,
         "tx_packets": 111532
      }   
```
As you can see there are a few interfaces, but only the first one is read, resulting in 0's for the stats. Ideally the values from all interfaces should be summed up.

### Steps to reproduce

Start a container (such as Homepage!) that uses multiple network interfaces. Let it do its thing for a while. View usage stats. Marvel at the 0's or other inaccurate numbers.

### homepage version

v0.8.0 (b019295, Nov 8, 2023)

### Installation method

Docker

### Troubleshooting

I spent over a day trying to figure this out, switching from docker socket to proxy, messing with homepage/swarm settings and labels... and it turned out to be something way more simple.
For some reason Portainer has the same issue with the network stats/graphs.

### Other

Docker version 24.0.7, build afdd53b4e3

### Before submitting, I have made sure to

- [x] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Thats because we just get the stats from the docker API, we literally dont even modify it
https://github.com/gethomepage/homepage/blob/392b2c309509e953f092643a513b10e771999cf0/src/pages/api/docker/stats/%5B...service%5D.js#L66
https://github.com/gethomepage/homepage/blob/392b2c309509e953f092643a513b10e771999cf0/src/widgets/docker/component.jsx#L54

Unfortunately theres not much we can do here on our end

**Comment by shamoon** [comment]
Oh wait

**Comment by prokrypt** [comment]
> Oh wait

I just saw it too, LOL :D

**Comment by shamoon** [comment]
Yea found some evidence that this is what we should be doing, thanks
