### ISSUE TITLE
[Bug] The text for the unifi controller widget wraps to a new line and causes a UI issue

### ISSUE THREAD

**Issue by dontcrash** [gethomepage/homepage#2388]
### Description

The "System Uptime" text wraps to a new line and causes this one widget to have a height larger than all other widgets

![image](https://github.com/gethomepage/homepage/assets/32660358/1372a02c-f36a-4311-b560-093e99cbe53e)

Changing the text to "Uptime" resolves this issue

![image](https://github.com/gethomepage/homepage/assets/32660358/346f5706-5d04-4db0-94dd-ef6fe90d1ab4)

This would also be in line with what Ubiquiti call it themselves
![image](https://github.com/gethomepage/homepage/assets/32660358/db58261f-0ead-4dbe-a193-d5d004956f5f)

### Steps to reproduce

N/A

### homepage version

Latest

### Installation method

Docker

### Troubleshooting

N/A

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
This is not a bug, it’s text wrapping. Many widgets do this
