### ISSUE TITLE
[Bug] Service icons broken

### ISSUE THREAD

**Issue by PinguCloud** [gethomepage/homepage#2390]
### Description

Since updating to version v0.8.2 all icons are broken and only show "logo".
Log does not contain any related errors.

The container seems to be unable to reach the icons-url.

Any ideas how to track down this issue? 

### Steps to reproduce

Open homepage.

### homepage version

v0.8.2

### Installation method

Docker

### Troubleshooting

Container has been recreated several times with no effect.
Tried clearing cache and different browser.

### Other

My container does not use host-network but has its own ip through mac-vlan.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
https://github.com/StevenBlack/hosts/issues/2515

**Comment by Bykow** [comment]
Indeed, in pihole:
Tools -> Update Gravity 

Fixed the issue for me

**Comment by cainnz** [comment]
> Indeed, in pihole: Tools -> Update Gravity
> 
> Fixed the issue for me

Thank you! this also fixed my icons issue.
