### ISSUE TITLE
k3s CPU Utilization not correct for service widgets

### ISSUE THREAD

**Issue by shadofall** [gethomepage/homepage#2424]
### Description

Current CPU Utilization for k3s not correct. not sure how it's supposed to be calculated after looking at the code, but i can let Jellyfin run with 16 threads (16000m in k3s terms) and have it max out with CPU bound transcoding and instead of telling my its using 50% of my cpu  or 100% of the CPU Limit applied to the app it stays at 0 or 1%

### Steps to reproduce

see Description for how i tested this

### homepage version

V0.8.2

### Installation method

Other (please describe above)

### Troubleshooting

Not sure what to provide other than some screenshots maybe since there's no actual error message

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Sorry here, but yea https://github.com/gethomepage/homepage/blob/708e6fa7894fa843f1f72b08b901cf17a9e2ded7/src/pages/api/kubernetes/stats/%5B...service%5D.js#L82-L84

**Comment by shadofall** [comment]
current cpu limit is 16    not sure how to confirm how homepage see's it

k3s kubectl get pods -o=jsonpath='{.items..resources.limits}' -n ix-jellyfin
{"cpu":"16","memory":"16Gi"} {"cpu":"16","memory":"16Gi","nvidia.com/gpu":"1"}

**Comment by shadofall** [comment]
> > and this is metrics output of jellyfin cpu transcoding
> > ![image](https://private-user-images.githubusercontent.com/9327622/287539953-04805431-b3e3-46dd-bd27-2767ef0c5602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MzM4OTMsIm5iZiI6MTcwMTYzMzU5MywicGF0aCI6Ii85MzI3NjIyLzI4NzUzOTk1My0wNDgwNTQzMS1iM2UzLTQ2ZGQtYmQyNy0yNzY3ZWYwYzU2MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMTk1OTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWNlZTNkODEzNjg4NDY1MDg1ZTI2YTBkMGJlMjg0OWE2MmE5MWEzODU1ZjMxYjMyODBjNDQ3NTZmMGNmYjIzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K7ZchvTYbBzIJ5n2QgDQiMEQ1faj5RqGFH0g-osOndk) using about 13/14 threads
> > and homepage saying 0%
> > ![image](https://private-user-images.githubusercontent.com/9327622/287539983-5d02ce0e-dea6-407f-aff8-677442679f49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MzM4OTMsIm5iZiI6MTcwMTYzMzU5MywicGF0aCI6Ii85MzI3NjIyLzI4NzUzOTk4My01ZDAyY2UwZS1kZWE2LTQwN2YtYWZmOC02Nzc0NDI2NzlmNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMTk1OTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmMxNjA0NDUzNzdkMGY2MDI4NThiMmUxZDlkNTJkYWZlZmE5NmUzZjA4OTg1NzdhMDg4M2IxMjI2Y2JhNWI3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.A073hUyh7Bxyern-_CnSNuGvRNiYI7Q9B-Z8TOhaIiA)
> 
> Try a `docker stats jellyfin` and see what it says, thats where the CPU usage comes from.

no docker runtimes are installed in this k3s kube setup.  so no docker status command  so cant be where is pulling stats from. atleast not the mem since it does report my mem.

the above screenshot would be k3s kubectl top pods -n <namespace>

**Comment by shamoon** [comment]
need to look when I’m back in front of my machine but think parseCpu might be the issue

**Comment by shadofall** [comment]
I havent set pod selector. its just blank. my impression was it would select all the pods in the namespace in that situation, is that wrong?

homepage
{"stats":{"mem":220960000,"cpu":0.001627681,"cpuLimit":8,"memLimit":16000000000,"cpuUsage":0.000203460125,"memUsage":0.01381}}

Jellyfin before and during transcode
{"stats":{"mem":756944000,"cpu":0.005289083,"cpuLimit":32,"memLimit":32000000000,"cpuUsage":0.00016528384375,"memUsage":0.0236545}}

{"stats":{"mem":4760680000,"cpu":13.727196436000002,"cpuLimit":32,"memLimit":32000000000,"cpuUsage":0.42897488862500005,"memUsage":0.14877125}}

**Comment by shamoon** [comment]
So would `"cpu":13.727196436000002,"cpuLimit":32,` --> .428 be correct assuming it was a percentage (42%)? Could it really be that the number just needs to be *100 and no one has noticed this before?? Before changing anything I'd love some confirmation. How about @jameswynn any thoughts here?

**Comment by shadofall** [comment]
from a raw numbers stand point that sounds about right .  and to be fair how many people probably just checked the metric part of the widget saw the ram count figured the CPU was just 0 because the app idle and moved on with yay it works  or have their CPU limit set low enough that they get a reading,  on average Jellyfin unless doing cpu transcoding, its barely using 1% of a single thread on my system so seeing a bunch of 0% is expected

i probably would not  of given it much thought my self except i was curious if the CPU utilization was  additive or averaged across the namespace  or based on max system cpu so i intentionally drove the cpu usage up.

**Comment by shamoon** [comment]
Ok, well not much input here, I'm going to merge a change that does that, if its wrong Im sure we'll hear about it =)
