### ISSUE TITLE
[Bug] Random glitches in the icons

### ISSUE THREAD

**Issue by dtypo** [gethomepage/homepage#2425]
### Description

Hello!
I'm having strange glitches in my homepage.
The icons with glitches are regular PNGs and the glitches tend to disappear when zooming in.
I tried even resizing them, but without success.
Attached you can find some of the affected PNGs.
Any idea? 

![image](https://github.com/gethomepage/homepage/assets/40309637/1e39db4c-fe63-40be-bcf7-9a27644a32a5)
![filebrowser](https://github.com/gethomepage/homepage/assets/40309637/a91e0f6d-1018-474c-bb7d-ae5ff1e66079)
![nas](https://github.com/gethomepage/homepage/assets/40309637/9148ffac-d3e7-463b-b3df-58e08e0e7257)
![qbittorrent](https://github.com/gethomepage/homepage/assets/40309637/d3c1d020-c588-4809-893a-5673b134c030)

### Steps to reproduce

n/a

### homepage version

v0.7.1

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I apologize if that came across as gruff but no one has ever reported this before, I cannot reproduce this and we do not have anything to do with the icons. The code that generates them is incredibly basic, just essentially an html tag. So overall I don’t think this is a “bug” in homepage, which is what opening an issue here implies.

Perhaps it’s more appropriate as a discussion to see if anyone has a better idea
