### ISSUE TITLE
[Bug] fritzbox proxy fails when no value returned in response

### ISSUE THREAD

**Issue by evorg** [gethomepage/homepage#2461]
### Description

As reported by @alexdelprete [here](https://github.com/gethomepage/homepage/discussions/1213#discussioncomment-7811181) and specified in more detail [here](https://github.com/gethomepage/homepage/discussions/1213#discussioncomment-7811844), an error occurs in the fritzbox proxy if a property of the devices SOAP response has no value.

For example:
```
...
<NewDNSServer2></NewDNSServer2>
...
```

Results in:
```
{
  "error": "Failed parsing 'GetStatusInfo' response"
}
```

### Steps to reproduce

Ensure that a property is not set and embed the fritzbox widget.

### homepage version

v0.8.3

### Installation method

Other (please describe above)

### Troubleshooting

```console
[2023-12-10T12:26:53.909Z] debug: <fritzboxProxyHandler> Failed parsing WANCommonInterfaceConfig->GetAddonInfos response: <Buffer 3c 3f 78 6d 6c 20 76 65 72 73 69 6f 6e 3d 22 31 2e 30 22 20 65 6e 63 6f 64 69 6e 67 3d 22 75 74 66 2d 38 22 3f 3e 0a 3c 73 3a 45 6e 76 65 6c 6f 70 65 ... 1086 more bytes>
```

_Originally posted by @alexdelprete in https://github.com/gethomepage/homepage/discussions/1213#discussioncomment-7811291_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Am I correct in assuming you’re planning to fix this? (Not a rush just asking)

**Comment by evorg** [comment]
Wow @shamoon, your response time is way too fast! 😁 😁 😁 
I just pushed a fix for this ...

**Comment by shamoon** [comment]
Ha, yes sorry about that, was in front of my machine (which it seems I am lot 🤔) =)
