### ISSUE TITLE
[Bug] Concise description of the issue

### ISSUE THREAD

**Issue by slayoffer** [gethomepage/homepage#2517]
### Description

Hello.

Immich widget API url should be changed from "/api/server-info/stats" to "/api/server-info/statistics"

Looks like API token is not needed anymore to get stats.

### Steps to reproduce

Activate Immich widget

### homepage version

v0.7.1

### Installation method

Docker

### Container Logs

error: <credentialedProxyHandler> HTTP Error 404 calling https://immich.url.app/api/server-info/stats

### Troubleshooting

error: <credentialedProxyHandler> HTTP Error 404 calling https://immich.url.app/api/server-info/stats

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
#2283

**Comment by shamoon** [comment]
Sorry this one https://github.com/gethomepage/homepage/pull/2284
