### ISSUE TITLE
[Bug] Openmediavualt widgets password can't be purely numeric

### ISSUE THREAD

**Issue by soilderjames** [gethomepage/homepage#2554]
### Description

If the password is purely numeric, return error “password is not a string”

{"response":null,"error":{"code":0,"message":"password: The value 12345678 is not a string.","trace":"OMV\\Json\\SchemaValidationException: password: The value 12345678 is not a string. in \/usr\/share\/php\/openmediavault\/json\/schema.inc:370\nStack trace:\n#0 \/usr\/share\/php\/openmediavault\/json\/schema.inc(301): OMV\\Json\\Schema->validateString()\n#1 \/usr\/share\/php\/openmediavault\/json\/schema.inc(631): OMV\\Json\\Schema->validateType()\n#2 \/usr\/share\/php\/openmediavault\/json\/schema.inc(399): OMV\\Json\\Schema->checkProperties()\n#3 \/usr\/share\/php\/openmediavault\/json\/schema.inc(289): OMV\\Json\\Schema->validateObject()\n#4 \/usr\/share\/php\/openmediavault\/json\/schema.inc(261): OMV\\Json\\Schema->validateType()\n#5 \/usr\/share\/php\/openmediavault\/rpc\/paramsvalidator.inc(59): OMV\\Json\\Schema->validate()\n#6 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(179): OMV\\Rpc\\ParamsValidator->validate()\n#7 \/var\/www\/openmediavault\/rpc\/session.inc(50): OMV\\Rpc\\ServiceAbstract->validateMethodParams()\n#8 [internal function]: OMVRpcServiceSession->login()\n#9 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(123): call_user_func_array()\n#10 \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod()\n#11 \/usr\/share\/php\/openmediavault\/rpc\/proxy\/json.inc(97): OMV\\Rpc\\Rpc::call()\n#12 \/var\/www\/openmediavault\/rpc.php(45): OMV\\Rpc\\Proxy\\Json->handle()\n#13 {main}"}}

### Steps to reproduce

1.Set password to pure numbers.
2.Set Openmediavualt widgets.
3.Visit homepage then return the api error.

### homepage version

v0.8.4

### Installation method

Docker

### Configuration

```yaml
- OpenMediavault:
        icon: openmediavault.png
        href: http://192.168.1.128
        siteMonitor: http://192.168.1.128
        widget:
          type: openmediavault
          url: http://192.168.1.128
          username: admin
          password: 12345678
          method: services.getStatus
```

### Troubleshooting

{"response":null,"error":{"code":0,"message":"password: The value 12345678 is not a string.","trace":"OMV\\Json\\SchemaValidationException: password: The value 12345678 is not a string. in \/usr\/share\/php\/openmediavault\/json\/schema.inc:370\nStack trace:\n#0 \/usr\/share\/php\/openmediavault\/json\/schema.inc(301): OMV\\Json\\Schema->validateString()\n#1 \/usr\/share\/php\/openmediavault\/json\/schema.inc(631): OMV\\Json\\Schema->validateType()\n#2 \/usr\/share\/php\/openmediavault\/json\/schema.inc(399): OMV\\Json\\Schema->checkProperties()\n#3 \/usr\/share\/php\/openmediavault\/json\/schema.inc(289): OMV\\Json\\Schema->validateObject()\n#4 \/usr\/share\/php\/openmediavault\/json\/schema.inc(261): OMV\\Json\\Schema->validateType()\n#5 \/usr\/share\/php\/openmediavault\/rpc\/paramsvalidator.inc(59): OMV\\Json\\Schema->validate()\n#6 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(179): OMV\\Rpc\\ParamsValidator->validate()\n#7 \/var\/www\/openmediavault\/rpc\/session.inc(50): OMV\\Rpc\\ServiceAbstract->validateMethodParams()\n#8 [internal function]: OMVRpcServiceSession->login()\n#9 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(123): call_user_func_array()\n#10 \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod()\n#11 \/usr\/share\/php\/openmediavault\/rpc\/proxy\/json.inc(97): OMV\\Rpc\\Rpc::call()\n#12 \/var\/www\/openmediavault\/rpc.php(45): OMV\\Rpc\\Proxy\\Json->handle()\n#13 {main}"}}

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by Ayu5hsingh** [comment]
Can I work on this issue?

**Comment by shamoon** [comment]
Have you confirmed their api accepts that value as a string?

**Comment by Ayu5hsingh** [comment]
No haven't confirmed yet, will do that.

**Comment by shamoon** [comment]
https://github.com/gethomepage/homepage/pull/2555
