### ISSUE TITLE
[Bug] PI Alerts API no longer works 

### ISSUE THREAD

**Issue by Scottmmwood** [gethomepage/homepage#2602]
### Description

PI alerts Api gives HTTP error 

API Error: HTTP Error
URL: http://10.1.2.200/php/server/devices.php?action=getDevicesTotals

### Steps to reproduce

Set up PI Alerts API using widget instructions 

### homepage version

v0.8.4 - https://tteck.github.io/Proxmox/

### Installation method

Other (please describe above)

### Troubleshooting

Updated all services, tested with API Key with and without reverse proxy 

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please post your output from the troubleshooting guide as required in the template. Nothing has changed that Im aware of.
