### ISSUE TITLE
[Bug] CustomAPI with Docker Service Discovery doesn't work

### ISSUE THREAD

**Issue by arhue** [gethomepage/homepage#2603]
### Description

Specifying customAPI with Docker Service Discovery doesn't work. I am specifically using Docker in Swarm mode. Not confirmed if t he same does/does not work in standalone mode.

Related discussion here: https://github.com/gethomepage/homepage/discussions/2574

### Steps to reproduce

1. Add labels for widget with Custom API
Eg. 

```
labels:
      - homepage.group=Downloaders
      - homepage.name=Kapowarr
      - homepage.href=http://kapowarr.loc.com
      - homepage.description=Comics management
      - homepage.widget.type=customapi
      - homepage.widget.url=http://kapowarr.loc.com/api/volumes/stats?api_key=$KAPOWARR_API_KEY
      - homepage.widget.field[0].label=Series
      - homepage.widget.field[0].field.result=volumes
```

2. The customAPI widget doesn't show up.

### homepage version

v0.8.4 32f28d3 

### Installation method

Docker

### Configuration

```yaml
labels:
      - homepage.group=Downloaders
      - homepage.name=Kapowarr
      - homepage.href=http://kapowarr.loc.com
      - homepage.description=Comics management
      - homepage.widget.type=customapi
      - homepage.widget.url=http://kapowarr.loc.com/api/volumes/stats?api_key=$KAPOWARR_API_KEY
      - homepage.widget.field[0].label=Series
      - homepage.widget.field[0].field.result=volumes
```

### Troubleshooting

Nothing relevant in logs

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
> Specifying customAPI with Docker Service Discovery doesn't work

I dont think thats accurate

```
      - homepage.widget.type=customapi
      - homepage.widget.url=https://rickandmortyapi.com/api/character/1
      - homepage.widget.mappings[0].field=name
      - homepage.widget.mappings[0].label=Name
      - homepage.widget.mappings[1].field.location=name
      - homepage.widget.mappings[1].label=Location
```

<img width="597" alt="Screenshot 2024-01-10 at 10 46 24 AM" src="https://github.com/gethomepage/homepage/assets/4887959/257407ba-e1c5-47f2-a1ce-a5445bb2f18f">

**Comment by arhue** [comment]
@shamoon That did not work for me either. Are you using it in Swarm mode or in standalone mode? There are other people in the discussion who have reported the same issue.

**Comment by aeikenberry** [comment]
Might just be a documentation issue, you're using mappings[] in your label, but the docs say fields[].

**Comment by arhue** [comment]
@aeikenberry Did mappings[] work for you? It did not work for me in Swarm mode.

**Comment by aeikenberry** [comment]
![Screenshot 2024-01-10 at 1 25 03 PM](https://github.com/gethomepage/homepage/assets/599112/bf297bb8-0773-426b-b7d0-b570ac410bf7)

```
      - homepage.widget.type=customapi
      - homepage.widget.url=http://kapowarr.loc.com/api/volumes/stats?api_key=$KAPOWARR_API_KEY
      - homepage.widget.mappings[0].field.result=volumes
      - homepage.widget.mappings[0].label=Volumes
      - homepage.widget.mappings[1].field.result=issues
      - homepage.widget.mappings[1].label=Issues
      - homepage.widget.mappings[2].field.result=files
      - homepage.widget.mappings[2].label=Files
```
Works for me, thanks!

**Comment by arhue** [comment]
Nvm, got it to work with mappings as well. Thanks everyone, sorry about the confusion.
