### ISSUE TITLE
[Bug] Concise description of the issue

### ISSUE THREAD

**Issue by Edysers** [gethomepage/homepage#2618]
### Description

There is a problem with the parts, I can see this on the speedtest tracker.
API ERROR INFORMATION 
API Error: HTTP Error
URL: http://192.xxx.xxx.xxx:8999//api/speedtest/latest

### Steps to reproduce

.

### homepage version

v0.8.0 (b019295)

### Installation method

Docker

### Troubleshooting

API Error: HTTP Error
URL: http://192.168.1.158:8999//api/speedtest/latest

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please follow the troubleshooting guide, this is not sufficient to constitute a bug

**Comment by Edysers** [comment]
I couldn't find it in that troubleshooting guide
