### ISSUE TITLE
[Bug] Widgets will show API Error when not in a group

### ISSUE THREAD

**Issue by heikomat** [gethomepage/homepage#2620]
### Description

When a widget is not in a group, for example because the corresponding service was discovered via docker labels and no group was configured, then the widget will be displayed, but with an API Error:

![Screenshot 2024-01-13 at 00 01 58](https://github.com/gethomepage/homepage/assets/20770029/dcf4593c-ab07-44a2-8e72-b8995eaeae38)

Finding the reason took some time because
- The error message of the corresponding API call is misleading (the issue is actually unrelated to the services API)
- It was not clear what API was misbehaving

The website made the following call that failed:
```
https://<my-homepage-domain>/api/services/proxy?type=adguard&group=undefined&service=Adguard&endpoint=stats
```
It failed with a 403 and the following content:
```json
{"error":"Service does not support API calls"}
```

only upon closer inspection i noticed the `group=undefined` within the url and guessed that that might not be ok.
As soon as i put the service in a group, the API call works again.

While all examples in the documentation configure a group, i have not found a mention of that being a requirement.

I would expect one of two things:
- Either the docs should clearly state that widgets must be in a group
- Or that a widget not being in a group doesn't make the api call fail (because why would the grouping change anything about the call to my services api?)

### Steps to reproduce

- configure a service (for example adguard or immich) without a group (for example via docker labels)
- open the homepage
- observe the API error

### homepage version

v0.8.4 (32f28d3, Dec 27, 2023)

### Installation method

Docker

### Troubleshooting

docker exec homepage ping <my-adguard-domain>
PING <my-adguard-domain> (192.168.178.20): 56 data bytes
64 bytes from 192.168.178.20: seq=0 ttl=64 time=0.043 ms
64 bytes from 192.168.178.20: seq=1 ttl=64 time=0.063 ms
64 bytes from 192.168.178.20: seq=2 ttl=64 time=0.065 ms
64 bytes from 192.168.178.20: seq=3 ttl=64 time=0.063 ms

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
It is a requirement and always has been. Feel free to PR the docs if you think that needs to be stated somewhere, tho in ~2 years no one has ever misconstrued this, to my knowledge

**Comment by heikomat** [comment]
Thanks for the quick response!

I might PR the docs if i find some time :)
