### ISSUE TITLE
[Bug] authorization issue Unifi Wigdet

### ISSUE THREAD

**Issue by ironboy1** [gethomepage/homepage#2635]
### Description

Hi, I'm trying to setup the unifi controller widget, but unfortunately I'm getting always the same error message back:
API-Fehler: HTTP Error 401
URL: https://10.10.2.1/api/stat/sites
Antwortdaten:
{"error":{"code":401,"message":"Unauthorized"}}

I checked the credentials 10 times, and selceted user is also working. Same user is used for the home assistant unifi integration.

I'm running an UDM SE @ Unifi OS 3.2.7

### Steps to reproduce

configure unifi controller widget
and run it against a UDM SE 

### homepage version

latest docker image

### Installation method

Docker

### Container Logs

2024-01-16T00:54:45.782Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}

### Troubleshooting

docker logs: [2024-01-16T00:54:45.782Z] error: <unifiProxyHandler> HTTP 401 logging in to Unifi. Data: {"error":{"code":401,"message":"Unauthorized"}}

sudo docker exec homepage ping 10.10.2.1
PING 10.10.2.1 (10.10.2.1): 56 data bytes
64 bytes from 10.10.2.1: seq=0 ttl=63 time=0.173 ms
64 bytes from 10.10.2.1: seq=1 ttl=63 time=0.269 ms
64 bytes from 10.10.2.1: seq=2 ttl=63 time=0.423 ms
64 bytes from 10.10.2.1: seq=3 ttl=63 time=0.316 ms
64 bytes from 10.10.2.1: seq=4 ttl=63 time=0.350 ms

successful curl login request:
/usr/bin/curl --insecure -c /tmp/unifiCookie -H "Content-Type: application/json" --data '{
    "username": "Censored-User",
    "strict": "True",
    "password": "Censored-password"
}' 'https: //10.10.2.1:443/api/
auth/login'
{
    "unique_id": "Censored-UID",
    "first_name": "Censored-User",
    "last_name": " ",
    "alias": "",
    "full_name": "Censored-User  ",
    "email": "",
    "email_status": "UNVERIFIED",
    "email_is_null": true,
    "phone": "",
    "avatar_relative_path": "",
    "avatar_rpath2": "",
    "status": "ACTIVE",
    "employee_number": "",
    "create_time": 1704786548,
    "login_time": 1705219274,
    "extras": {},
    "username": "Censored-User",
    "local_account_exist": true,
    "password_revision": 1704786548,
    "sso_account": "",
    "sso_uuid": "",
    "sso_username": "",
    "sso_picture": "",
    "uid_sso_id": "",
    "uid_sso_account": "",
    "uid_account_status": "",
    "groups": [
        {
            "unique_id": "Censored-UID2",
            "name": "Censored-name",
            "up_id": "",
            "up_ids": [],
            "system_name": "Censored-name",
            "create_time": "2023-12-28T16:40:03+01:00"
        }
    ],
    "roles": [
        {
            "unique_id": "Censored-UID3",
            "name": "role_private_XXX",
            "system_role": false,
            "system_key": "custom_administrator_cXXX",
            "level": 5,
            "create_time": "2024-01-16T01:44:50+01:00",
            "update_time": "2024-01-16T01:44:50+01:00",
            "is_private": true
        }
    ],
    "permissions": {
        "access.management": [
            "readonly"
        ],
        "network.management": [
            "admin"
        ],
        "protect.management": [
            "admin"
        ],
        "system.management.user": [
            "admin"
        ]
    },
    "scopes": [
        "write:protect.viewer",
        "write:protect.user:$",
        "write:protect.user",
        "write:protect.sensor",
        "write:protect.schedule",
        "write:protect.nvr",
        "write:protect.light",
        "write:protect.legacyUFV",
        "write:protect.group",
        "write:protect.doorlock",
        "write:protect.display",
        "write:protect.deviceGroup",
        "write:protect.chime",
        "write:protect.camera",
        "write:protect.bridge",
        "view:wifi",
        "view:vpn",
        "view:user_timezone",
        "view:user",
        "view:unifi-os:user",
        "view:systemlog",
        "view:settings",
        "view:role",
        "view:permission",
        "view:os-menu:user",
        "view:os-menu:system-log",
        "view:os-menu:storage",
        "view:os-menu:settings",
        "view:os-menu:notify-settings",
        "view:os-menu:map",
        "view:os-menu:devices",
        "view:os-menu:about",
        "view:notification",
        "view:location_policy",
        "view:location_device",
        "view:location_activity",
        "view:location",
        "view:holiday_timezone",
        "view:holiday",
        "view:group",
        "view:door_group",
        "view:controller:protect",
        "view:controller:network",
        "view:controller:access",
        "view:cloud_access",
        "view:app:users",
        "view:app:settings",
        "view:access:user",
        "view:access.visitor",
        "view:access.systemlog",
        "view:access.settings",
        "view:access.schedule",
        "view:access.policy",
        "view:access.pin_code",
        "view:access.open_api",
        "view:access.nfc_card",
        "view:access.face",
        "view:access.device",
        "view:access.dashboard",
        "systemlog:user",
        "systemlog:system",
        "systemlog:network",
        "systemlog:location",
        "systemlog:connect",
        "systemlog:access",
        "readmedia:protect.camera",
        "read:protect.viewer",
        "read:protect.user:$",
        "read:protect.user",
        "read:protect.sensor",
        "read:protect.schedule",
        "read:protect.nvr",
        "read:protect.light",
        "read:protect.legacyUFV",
        "read:protect.group",
        "read:protect.doorlock",
        "read:protect.display",
        "read:protect.deviceGroup",
        "read:protect.chime",
        "read:protect.camera",
        "read:protect.bridge",
        "notify:user",
        "notify:location",
        "notify:access",
        "manage:controller:protect",
        "manage:controller:network",
        "edit:wifi",
        "edit:vpn",
        "edit:user",
        "edit:unifi-os:user_group",
        "edit:unifi-os:user",
        "edit:settings",
        "edit:role",
        "edit:os-settings:update_install",
        "edit:os-settings:support_file",
        "edit:os-settings:ssh",
        "edit:os-settings:send_diagnostics",
        "edit:os-settings:restart",
        "edit:os-settings:raid",
        "edit:os-settings:poweroff",
        "edit:os-settings:notify",
        "edit:os-settings:hotspare",
        "edit:os-settings:general",
        "edit:os-settings:client_network",
        "edit:os-settings:auto_update",
        "edit:group",
        "edit:feedback",
        "edit:access.policy",
        "edit:access.pin_code",
        "edit:access.nfc_card",
        "deletemedia:protect.camera",
        "delete:protect.viewer",
        "delete:protect.user:$",
        "delete:protect.user",
        "delete:protect.sensor",
        "delete:protect.schedule",
        "delete:protect.nvr",
        "delete:protect.light",
        "delete:protect.legacyUFV",
        "delete:protect.group",
        "delete:protect.doorlock",
        "delete:protect.display",
        "delete:protect.deviceGroup",
        "delete:protect.chime",
        "delete:protect.camera",
        "delete:protect.bridge",
        "credential:send_email",
        "create:protect.viewer",
        "create:protect.user",
        "create:protect.sensor",
        "create:protect.schedule",
        "create:protect.liveview",
        "create:protect.light",
        "create:protect.group",
        "create:protect.doorlock",
        "create:protect.display",
        "create:protect.deviceGroup",
        "create:protect.chime",
        "create:protect.camera",
        "create:protect.bridge",
        "assign:wifi",
        "assign:vpn",
        "assign:role",
        "assign:evstation"
    ],
    "cloud_access_granted": false,
    "only_local_account": true,
    "update_time": 1704786548,
    "avatar": null,
    "nfc_token": "",
    "nfc_display_id": "",
    "nfc_card_type": "",
    "nfc_card_status": "",
    "role": "custom",
    "roleId": "Censored-UID3",
    "id": "Censored-UID",
    "isOwner": false,
    "isSuperAdmin": false,
    "isMember": false,
    "maskedEmail": "",
    "accessMask": 1218,
    "permissionMask": 8012,
    "deviceToken": "censored device-token",
    "ssoAuth": {}
}

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please search. There are a lot of these, very rarely are any of them truly a bug.
