### ISSUE TITLE
[Bug] Docker services not discorvered after latest update

### ISSUE THREAD

**Issue by Dart2112** [gethomepage/homepage#2715]
### Description

Discovery worked fine on the previous version (0.8.4), updated to the latest version overnight and now I get this message when I enable debug

debug: No containers were found with homepage labels.

Rolling back to 0.8.4 fixes the issue

### Steps to reproduce

Use lables for docker discovery

Update to 0.8.5

Reload homepage and find discovered services missing

### homepage version

v0.8.5

### Installation method

Docker

### Configuration

```yaml
Docker.yml

server:
  socket: /var/run/docker.sock
```

### Container Logs

[2024-01-21T05:21:44.896Z] debug: No containers were found with homepage labels.

### Troubleshooting

see above

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by Dart2112** [comment]
dnablue2112 on Discord

**Comment by shamoon** [comment]
You also didnt post much configuration...

**Comment by shamoon** [comment]
Is there anything in the browser console?

**Comment by Dart2112** [comment]
Browser console only shows one error

AbortError: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved [ConduitsParent.sys.mjs:362](resource://gre/modules/ConduitsParent.sys.mjs)

    _raceResponses resource://gre/modules/ConduitsParent.sys.mjs:362

**Comment by Dart2112** [comment]
[HomepageConfig.zip](https://github.com/gethomepage/homepage/files/14000267/HomepageConfig.zip)

This is the entire config directory, I've only excluded my bookmarks for privacy

**Comment by chall4478** [comment]
I have the same issue with 0.8.5.   Similar configuration as Dart2112.

**Comment by shamoon** [comment]
Sorry everyone, silly mistake, should have a fix shortly

**Comment by shamoon** [comment]
v0.8.6 is building right now (~15 minutes) and should fix this.

Thanks all

**Comment by ameeno** [comment]
Good. Just noticed this this morning. Watchtower won't update it for 24 hours :(

**Comment by ameeno** [comment]
Oh yes, good point, thanks for the tip, I am pulling the new one now.
