### ISSUE TITLE
Healthchecks new updated widget

### ISSUE THREAD

**Issue by Churator** [gethomepage/homepage#2749]
### Description

I'm getting this error when I remove the UUID from the widget of Healthchecks
API Error: Invalid data
URL: https://healthchecks.io/api/v2/checks/

Config:
- HealthChecks:
href: https://healthchecks.io/
icon: healthchecks
widget:
type: healthchecks
url: https://healthchecks.io/
key:

Fully response:
{"checks": [{"name": "LanSVC", "slug": "lansvc", "tags": "", "desc": "", "grace": 60, "n_pings": 27636, "status": "up", "started": false, "last_ping": "2024-01-21T13:56:01+00:00", "next_ping": "2024-01-21T13:58:00+00:00", "manual_resume": false, "methods": "", "subject": "", "subject_fail": "", "start_kw": "", "success_kw": "", "failure_kw": "", "filter_subject": false, "filter_body": false, "unique_key": "", "schedule": "*/2 * * * *", "tz": "Asia/Jerusalem"}, {"name": "Uptime Kuma", "slug": "uptime-kuma", "tags": "", "desc": "", "grace": 120, "n_pings": 492274, "status": "up", "started": false, "last_ping": "2024-01-21T13:56:04+00:00", "next_ping": "2024-01-21T13:58:04+00:00", "manual_resume": false, "methods": "", "subject": "", "subject_fail": "", "start_kw": "", "success_kw": "", "failure_kw": "", "filter_subject": false, "filter_body": false, "unique_key": "", "timeout": 120}]}

### Steps to reproduce

remove UUID from existing widget to see all checks statistics

### homepage version

0.8.4

### Installation method

Docker

### Troubleshooting

add UUID and I see the specific one

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Make sure you followed all the steps of the troubleshooting guide. Using the data you supplied (thanks) works fine:

<img width="740" alt="Screenshot 2024-01-24 at 2 29 27 PM" src="https://github.com/gethomepage/homepage/assets/4887959/baa0dcb8-a6c3-4a76-a746-a2851a1e6913">

Similarly, using real data works fine:

```yaml
     - Healthchecks:
          description: healthchecks
          icon: healthchecks.png
          href: https://healthchecks.io
          widget:
               url: https://healthchecks.io
               type: healthchecks
               key: **
```

<img width="744" alt="Screenshot 2024-01-24 at 2 28 52 PM" src="https://github.com/gethomepage/homepage/assets/4887959/a3ad535f-1812-459f-917d-0afb57f796cc">
