### ISSUE TITLE
[Bug] Container image missing `iputils` -- ping property fails

### ISSUE THREAD

**Issue by zimmertr** [gethomepage/homepage#2776]
### Description

I'm setting up Homepage (Very cool software btw!) for my homelab and think I found a bug with the `ping` integration. Here is an example configuration and a screenshot of the result:

```yaml
- Public:
  - Personal Website:
      description: tjzimmerman.com
      href: https://tjzimmerman.com
      icon: nginx.png
      ping: https://tjzimmerman.com
```

![Screenshot 2024-01-27 at 8 18 29 PM](https://github.com/gethomepage/homepage/assets/4356289/61df63b1-7b93-45b1-9392-d36161b9965c)

As you can see, Firefox's Web Developer Tools says the response is:

> output	"PING tjzimmerman.com (24.18.54.107): 56 data bytes\nping: permission denied (are you root?)\n"

I Googled that error and found [this ServerFault post](https://serverfault.com/a/1001312/423284), within which it suggests the error might be produced by Alpine when `iputils` is missing. 

If I then `exec` into the container and run `apk add iputils`, the pings start working. 

![Screenshot 2024-01-27 at 8 20 58 PM](https://github.com/gethomepage/homepage/assets/4356289/d23e97ea-df1b-4248-bb51-4250c77fcacd)

![Screenshot 2024-01-27 at 8 21 25 PM](https://github.com/gethomepage/homepage/assets/4356289/55de05a9-b9f0-41f8-a4b9-7ef422690c3d)

I'm a little confused because the docs indicate that the Ping integration isn't a true ICMP ping. But this error and solution suggests otherwise? 

### Steps to reproduce

Ping with `ghcr.io/gethomepage/homepage:v0.8.7`

### homepage version

v0.8.7

### Installation method

Other (please describe above)

### Troubleshooting

Noted above in Description field. 

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
From the docs: https://gethomepage.dev/latest/configs/services/#ping

> As of v0.8.0, the ping feature attempts to use a true (ICMP) ping command on the underlying host.

**Comment by shamoon** [comment]
Ps. I assume you’re looking for siteMonitor, same page in the docs

**Comment by zimmertr** [comment]
I somehow ended up on https://gethomepage.dev/v0.7.0/ and didn't realize it, so missed the part of the docs where icmp pings were mentioned. 

I don't understand why you closed this though. I just demonstrated that iputils isn't installed inside your container image? So pings will not work without that package?

**Comment by shamoon** [comment]
It’s trying to use ping on the host, eg your server and it seems has a permission issue but that is not a general issue that we’re seeing reported.

**Comment by zimmertr** [comment]
The host in this case is your container image.......
