### ISSUE TITLE
Cloudflare tunnel error

### ISSUE THREAD

**Issue by Adevill20** [gethomepage/homepage#2818]
When using the cloudflared widget I get the error below:

Widget configuration used:
- Main Environment Status:
    #- My First Service:
        #href: http://localhost/
        #description: Homepage is awesome
        
    - Cloudflare Tunnel:
        icon: si-cloudflare
        widget:
          type: cloudflared
          accountid: myaccountid
          tunnelid: cybercloud
          key: mykey

![image](https://github.com/gethomepage/homepage/assets/4531550/af3f920c-7362-468b-bc36-e0d1ad0c9e55)

**Comment by Adevill20** [comment]
For those having the same issue. You must use your Cloudflare tunnel ID, not NAME. I could only find the tunnel ID by using Postman and querying the API to list all tunnels.

**Comment by amtra** [comment]
even after using tunnel id same error.

[2024-02-15T18:44:04.893Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://api.cloudflare.com/client/v4/accounts/https://one.dash.cloudflare.com/xxxxxxxxxxxxxxxxxxxxxx/home/quick-start/cfd_tunnel/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by shamoon** [comment]
Just look at that URL, its clearly not configured correctly.
