### ISSUE TITLE
Quick Launch Feature Does Not Support Cyrillic Input

### ISSUE THREAD

**Issue by mrkhachaturov** [gethomepage/homepage#3084]
### Before submitting, please confirm the following

- [X] I confirm this was discussed, and the maintainers suggest I open an issue.
- [X] I am aware that if I create this issue without a discussion, it will be removed without a response.

### Discussion Link

https://github.com/gethomepage/homepage/discussions/3019

**Comment by shamoon** [comment]
#3020
