### ISSUE TITLE
[BUG] `gamedig` widget fails when `fields` specified in docker labels

### ISSUE THREAD

**Issue by dud1337** [gethomepage/homepage#3100]
### Before submitting, please confirm the following

- [X] I confirm this was discussed, and the maintainers suggest I open an issue (note that AI bots are not maintainers).
- [X] I am aware that if I create this issue without a discussion, it will be removed without a response.

### Discussion Link

https://github.com/gethomepage/homepage/discussions/3099

### Additional context

```Text
Thanks for this excellent piece of software.
```

**Comment by shamoon** [comment]
Once the main image is built (takes ~15m) you should be able to test this out. Thanks.
