### ISSUE TITLE
Pihole widget error when `ads_percentage_today` is string type

### ISSUE THREAD

**Issue by thisguyshouldworkforus** [gethomepage/homepage#3312]
### Before submitting, please confirm the following

- [X] I confirm this was discussed, and the maintainers suggest I open an issue (note that AI bots are not maintainers).
- [X] I am aware that if I create this issue without a discussion, it will be removed without a response.

### Discussion Link

https://github.com/gethomepage/homepage/discussions/3311

**Comment by shamoon** [comment]
Thanks, the fix for this should be in `main` when it builds in a bit and will be in our next release

<img width="441" alt="Screenshot 2024-04-16 at 3 44 24 PM" src="https://github.com/gethomepage/homepage/assets/4887959/443887c2-c03f-44d6-8152-a9e8e565a0b7">

**Comment by shamoon** [comment]
Ps. I dont know why your pihole returns data in a different format 🤷‍♂️

**Comment by thisguyshouldworkforus** [comment]
> Ps. I don't know why your pihole returns data in a different format 🤷‍♂️

It's running on a Pi4b, if that adds any context.
