### ISSUE TITLE
OPNSense widget - not fetching all fields as documented.

### ISSUE THREAD

**Issue by BBT-nZ** [gethomepage/homepage#4312]
What it should like per documentation: 
https://gethomepage.dev/widgets/services/opnsense/

![image](https://github.com/user-attachments/assets/2a54c2a7-d771-415a-8f0f-b3962cf20b8f)

What it looks like currently:
![image](https://github.com/user-attachments/assets/e54dacba-b0eb-40b0-9ed0-059c7bd2134a)

- OPNSense:
        icon: opnsense
        href: https://opnsense.mydomain.org/
        ping: https://opnsense.mydomain.org/
        description: Firewall
        widget:
          type: opnsense
          url: https://10.10.100.1
          username: abcdefghijklmnopqrts
          password: abcdefghijklmnopqrts
          fields: ["cpu", "memory", "wanUpload", "wanDownload"]

**OPNSense Version: 24.7.7-amd64**

Per documentation: 
Diagnostics: System Activity
**Status: Traffic Graph (this does not exists anymore)** and to investigate the issue, I've added all roles to the api user - no luck.

Believe, OPNSense being a core component of several people including me who love homepage would be epic if this issue can be resolve @dev's.

In addition, are there any plans to add more fields beyond these? Like interfaces, dhcp leases, WAN IP, total upload/download?
["cpu", "memory", "wanUpload", "wanDownload"]

This would be its worth in GOLD!

Thanks for all your hardwork

_Originally posted by @BBT-nZ in https://github.com/gethomepage/homepage/discussions/4203#discussioncomment-11328374_

**Comment by shamoon** [comment]
I said discussion =)
