### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LETRA** [gethomepage/homepage#670]
### Description

Create a Custom widget in widgets.yaml with this parameters:

- search:
    provider: custom
    focus: true
    url: http://192.168.188.52:5105/?q=
    target: _self

### Steps to reproduce

url: http://192.168.188.52:5105/?q= create a new Whoogle tab without query

### homepage version

last docker recipe vesion

### Installation method

Docker

**Comment by shamoon** [comment]
Sorry can you explain the bug more clearly?

**Comment by LETRA** [comment]
Thank you for your help. When I enter the code in widgets.yaml it opens the Whoogle self-hosted page but without the search terms.

I have tried with the urls:

http://192.168.188.52:5105/?q=

http://192.168.188.52:5105/?q=%s

http://192.168.188.52:5105/?q={query}

**Comment by shamoon** [comment]
Not aware of any problems with this, you didnt specify your homepage version in the form but there was an issue in the previous version.
Should just be `http://192.168.188.52:5105/?q=`

<img width="263" alt="Screen Shot 2022-12-12 at 11 22 57 AM" src="https://user-images.githubusercontent.com/4887959/207135586-1a8dc6e7-80a1-4f17-a457-abb5fd7ed8ed.png">

**Comment by Wdvh** [comment]
whoogle needs the word search before the ? like this: http://localhost:port/search?q=testing but the widget removes it and uses localhost:port/?q=testing that just opens a whoogle page but without the search term and not the results of the query
