### ISSUE TITLE
[Feature Request] Support for FRITZ!Box

### ISSUE THREAD

**Issue by update-freak** [gethomepage/homepage#810]
### Description

Hello developer,

it would be great if you could add support for FRITZ!Box, so that it is possible to see if the Guest-Wifi is activated or not. Furthermore it would be nice to see how many devices are connected and which ones.

**Comment by gordon848** [comment]
I'm also interested in support for Fritzbox/AVM. Also take a look into this #371

**Comment by t0rb3n** [comment]
@update-freak Not the developer here but I am currently working on getting the infos from #371 into homepage. 
Regarding the values you want. 
They should be possible but I would need input from the maintainers on how to do multiple requests with one widget.

In addition I am not sure how you could sensibly display all the names of the connected devices. Someone else would have to do that part.
